version: '3.1'
services:
  mysql:
    container_name: sequelize-cli-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sequelize-cli
      MYSQL_USER: sequelize-cli
      MYSQL_PASSWORD: 123456
    ports:
      - 3308:3306